// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VTA.API.DbContexts;

#nullable disable

namespace VTA.API.Migrations
{
    [DbContext(typeof(VTAContext))]
    partial class VTAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VTA.API.Models.Artefact", b =>
                {
                    b.Property<string>("ArtefactId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("artefactId");

                    b.Property<ushort>("ArtefactIndex")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("artefactIndex");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("categoryId");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagePath");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("modifiedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool?>("NameShown")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("nameShown");

                    b.Property<string>("SoundPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("soundPath");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("userID");

                    b.HasKey("ArtefactId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryId" }, "categoryId");

                    b.HasIndex(new[] { "UserId" }, "userId");

                    b.ToTable("artefact", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("categoryId");

                    b.Property<byte?>("CategoryIndex")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("categoryIndex");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagePath");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("lastUsedDate");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("modifiedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("usageCount");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("userId");

                    b.HasKey("CategoryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "userId")
                        .HasDatabaseName("userId1");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.Relation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("CaregiverId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("caregiver_id");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("ChildId");

                    b.ToTable("relation", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.SavedArtefact", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ArtefactId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("artefactId");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("boardId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<float>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(200f)
                        .HasColumnName("height");

                    b.Property<float>("PosX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("posX");

                    b.Property<float>("PosY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("posY");

                    b.Property<float>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(200f)
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ArtefactId" }, "artefactId");

                    b.HasIndex(new[] { "BoardId" }, "boardId");

                    b.ToTable("savedArtefact", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.SavedBoard", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ArtefactIds")
                        .HasColumnType("json")
                        .HasColumnName("artefactIds");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("modifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("SavedArtefactIds")
                        .HasColumnType("json")
                        .HasColumnName("savedArtefactIds");

                    b.Property<string>("SnapshotPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("snapshotPath");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "userId")
                        .HasDatabaseName("userId2");

                    b.ToTable("savedBoard", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("call_status");

                    b.Property<string>("CaregiverId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("caregiver_id");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("child_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("ChildId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Child")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.Artefact", b =>
                {
                    b.HasOne("VTA.API.Models.Category", "Category")
                        .WithMany("Artefacts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("artefact_ibfk_2");

                    b.HasOne("VTA.API.Models.User", "User")
                        .WithMany("Artefacts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("artefact_ibfk_1");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VTA.API.Models.Category", b =>
                {
                    b.HasOne("VTA.API.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("category_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VTA.API.Models.Relation", b =>
                {
                    b.HasOne("VTA.API.Models.User", "Caregiver")
                        .WithMany("CaregiverRelations")
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VTA.API.Models.User", "Child")
                        .WithMany("ChildRelations")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caregiver");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("VTA.API.Models.SavedArtefact", b =>
                {
                    b.HasOne("VTA.API.Models.Artefact", "Artefact")
                        .WithMany("SavedArtefacts")
                        .HasForeignKey("ArtefactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("savedArtefact_ibfk_1");

                    b.HasOne("VTA.API.Models.SavedBoard", "Board")
                        .WithMany("SavedArtefacts")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("savedArtefact_ibfk_2");

                    b.Navigation("Artefact");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("VTA.API.Models.SavedBoard", b =>
                {
                    b.HasOne("VTA.API.Models.User", "User")
                        .WithMany("SavedBoards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("savedBoard_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VTA.API.Models.Session", b =>
                {
                    b.HasOne("VTA.API.Models.User", "Caregiver")
                        .WithMany()
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_sessions_caregiver");

                    b.HasOne("VTA.API.Models.User", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_sessions_child");

                    b.Navigation("Caregiver");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("VTA.API.Models.Artefact", b =>
                {
                    b.Navigation("SavedArtefacts");
                });

            modelBuilder.Entity("VTA.API.Models.Category", b =>
                {
                    b.Navigation("Artefacts");
                });

            modelBuilder.Entity("VTA.API.Models.SavedBoard", b =>
                {
                    b.Navigation("SavedArtefacts");
                });

            modelBuilder.Entity("VTA.API.Models.User", b =>
                {
                    b.Navigation("Artefacts");

                    b.Navigation("CaregiverRelations");

                    b.Navigation("Categories");

                    b.Navigation("ChildRelations");

                    b.Navigation("SavedBoards");
                });
#pragma warning restore 612, 618
        }
    }
}
