// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VTA.API.DbContexts;

#nullable disable

namespace VTA.API.Migrations
{
    [DbContext(typeof(VTAContext))]
    partial class VTAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VTA.API.Models.Artefact", b =>
                {
                    b.Property<string>("ArtefactId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("artefactId");

                    b.Property<ushort>("ArtefactIndex")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("artefactIndex");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("categoryId");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagePath");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("modifiedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool?>("NameShown")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("nameShown");

                    b.Property<string>("SoundPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("soundPath");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("userID");

                    b.HasKey("ArtefactId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CategoryId" }, "categoryId");

                    b.HasIndex(new[] { "UserId" }, "userId");

                    b.ToTable("artefact", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("categoryId");

                    b.Property<byte?>("CategoryIndex")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("categoryIndex");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagePath");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("lastUsedDate");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("modifiedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("usageCount");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("userId");

                    b.HasKey("CategoryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "userId")
                        .HasDatabaseName("userId1");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.Invite", b =>
                {
                    b.Property<int>("InviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inviteId");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InviteId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expiresAt");

                    b.Property<int>("InviteStatus")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("RelationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("relationId");

                    b.HasKey("InviteId")
                        .HasName("PRIMARY");

                    b.HasIndex("RelationId")
                        .IsUnique();

                    b.HasIndex(new[] { "CreatedBy" }, "createdBy");

                    b.HasIndex(new[] { "RelationId" }, "relationId");

                    b.ToTable("invite", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.Relation", b =>
                {
                    b.Property<string>("RelationId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("relationId");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RelationType")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("relationType");

                    b.Property<string>("RelativeId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("relativeId");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("studentId");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");

                    b.HasKey("RelationId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RelativeId" }, "relativeId");

                    b.HasIndex(new[] { "StudentId" }, "studentId");

                    b.ToTable("relation", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.SavedArtefact", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ArtefactId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("artefactId");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("boardId");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<float>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(200f)
                        .HasColumnName("height");

                    b.Property<float>("PosX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("posX");

                    b.Property<float>("PosY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0f)
                        .HasColumnName("posY");

                    b.Property<float>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(200f)
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ArtefactId" }, "artefactId");

                    b.HasIndex(new[] { "BoardId" }, "boardId");

                    b.ToTable("savedArtefact", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.SavedBoard", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ArtefactIds")
                        .HasColumnType("json")
                        .HasColumnName("artefactIds");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdDate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("modifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("SavedArtefactIds")
                        .HasColumnType("json")
                        .HasColumnName("savedArtefactIds");

                    b.Property<string>("SnapshotPath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("snapshotPath");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("userId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "userId")
                        .HasDatabaseName("userId2");

                    b.ToTable("savedBoard", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("BoardId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("boardId");

                    b.Property<int?>("InviteId")
                        .HasColumnType("int")
                        .HasColumnName("inviteId");

                    b.Property<string>("RelationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("relationId");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BoardId" }, "boardId")
                        .HasDatabaseName("boardId1");

                    b.HasIndex(new[] { "InviteId" }, "inviteId")
                        .IsUnique();

                    b.HasIndex(new[] { "RelationId" }, "relationId")
                        .HasDatabaseName("relationId1");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("VTA.API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("firstName");

                    b.Property<string>("GuardianKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("guardianKey");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lastName");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("user", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VTA.API.Models.Admin", b =>
                {
                    b.HasBaseType("VTA.API.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("VTA.API.Models.Caregiver", b =>
                {
                    b.HasBaseType("VTA.API.Models.User");

                    b.Property<int?>("RelationType")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("relationType");

                    b.HasDiscriminator().HasValue("Caregiver");
                });

            modelBuilder.Entity("VTA.API.Models.Child", b =>
                {
                    b.HasBaseType("VTA.API.Models.User");

                    b.HasDiscriminator().HasValue("Child");
                });

            modelBuilder.Entity("VTA.API.Models.Artefact", b =>
                {
                    b.HasOne("VTA.API.Models.Category", "Category")
                        .WithMany("Artefacts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("artefact_ibfk_2");

                    b.HasOne("VTA.API.Models.User", "User")
                        .WithMany("Artefacts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("artefact_ibfk_1");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VTA.API.Models.Category", b =>
                {
                    b.HasOne("VTA.API.Models.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("category_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VTA.API.Models.Invite", b =>
                {
                    b.HasOne("VTA.API.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("invite_ibfk_user");

                    b.HasOne("VTA.API.Models.Relation", "Relation")
                        .WithOne("Invite")
                        .HasForeignKey("VTA.API.Models.Invite", "RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("VTA.API.Models.Relation", b =>
                {
                    b.HasOne("VTA.API.Models.Caregiver", "Relative")
                        .WithMany("CaregiverRelations")
                        .HasForeignKey("RelativeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("relation_ibfk_relative");

                    b.HasOne("VTA.API.Models.Child", "Student")
                        .WithMany("ChildRelations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("relation_ibfk_student");

                    b.Navigation("Relative");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("VTA.API.Models.SavedArtefact", b =>
                {
                    b.HasOne("VTA.API.Models.Artefact", "Artefact")
                        .WithMany("SavedArtefacts")
                        .HasForeignKey("ArtefactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("savedArtefact_ibfk_1");

                    b.HasOne("VTA.API.Models.SavedBoard", "Board")
                        .WithMany("SavedArtefacts")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("savedArtefact_ibfk_2");

                    b.Navigation("Artefact");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("VTA.API.Models.SavedBoard", b =>
                {
                    b.HasOne("VTA.API.Models.User", "User")
                        .WithMany("SavedBoards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("savedBoard_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VTA.API.Models.Session", b =>
                {
                    b.HasOne("VTA.API.Models.SavedBoard", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("session_ibfk_board");

                    b.HasOne("VTA.API.Models.Invite", "Invite")
                        .WithOne("Session")
                        .HasForeignKey("VTA.API.Models.Session", "InviteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VTA.API.Models.Relation", "Relation")
                        .WithMany("Sessions")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Invite");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("VTA.API.Models.Artefact", b =>
                {
                    b.Navigation("SavedArtefacts");
                });

            modelBuilder.Entity("VTA.API.Models.Category", b =>
                {
                    b.Navigation("Artefacts");
                });

            modelBuilder.Entity("VTA.API.Models.Invite", b =>
                {
                    b.Navigation("Session");
                });

            modelBuilder.Entity("VTA.API.Models.Relation", b =>
                {
                    b.Navigation("Invite");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VTA.API.Models.SavedBoard", b =>
                {
                    b.Navigation("SavedArtefacts");
                });

            modelBuilder.Entity("VTA.API.Models.User", b =>
                {
                    b.Navigation("Artefacts");

                    b.Navigation("Categories");

                    b.Navigation("SavedBoards");
                });

            modelBuilder.Entity("VTA.API.Models.Caregiver", b =>
                {
                    b.Navigation("CaregiverRelations");
                });

            modelBuilder.Entity("VTA.API.Models.Child", b =>
                {
                    b.Navigation("ChildRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
