name: Continuous Integration and Deployment

on:
  pull-request:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --framework net8.0 --verbosity normal

      - name: Publish the WebAPI
        if: success()
        run: dotnet publish --configuration Release --output ./output

      - name: Copy to deployment directory
        if: success()
        run: rsync -av --exclude='appsettings.json' --exclude='Assets/' ./output/ /var/www/VTA.API/

      - name: Set permissions for the assets folder
        run: sudo chmod 777 /var/www/VTA.API/Assets
        
      - name: Restart the service using SSH
        run: sudo systemctl restart vtaapi.service
