name: Continuous Integration

on:
  push:
    branches:
      - dev-main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Set environment variables for database connection
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: echo "Database environment variables set."

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Start SSH Tunnel for Database Access
        env:
          SSH_DOMAIN: ${{ secrets.SSH_DOMAIN }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "${SSH_PASSWORD}" ssh -f -o StrictHostKeyChecking=no -o ProxyCommand="cloudflared access ssh --hostname $SSH_DOMAIN" \
            -L 13306:localhost:3306 $SSH_USER@$SSH_DOMAIN -N

      - name: Run unit tests
        run: dotnet test --configuration Release --framework net8.0 --verbosity normal
