name: Continuous Integration and Deployment

on:
  pull_request:
    branches:
      - dev-main
      - main
  push:
    branches:
      - dev-main
      - main

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        env:
          SUDO_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
        run: |
          if ! command -v docker &> /dev/null; then
            echo "$SUDO_PASSWORD" | sudo -S apt-get update -y
            echo "$SUDO_PASSWORD" | sudo -S apt-get install -y docker.io
            echo "$SUDO_PASSWORD" | sudo -S usermod -aG docker ${{ secrets.RUNNER_USER }}
          fi

      - name: Ensure Docker is running
        env:
          SUDO_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
        run: |
          echo "$SUDO_PASSWORD" | sudo -S systemctl start docker

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --configuration Release --framework net8.0 --verbosity normal

      - name: Publish the WebAPI
        if: github.ref == 'refs/heads/main' && success()
        run: dotnet publish --configuration Release --output ./output

      - name: Copy to deployment directory
        if: github.ref == 'refs/heads/main' && success()
        run: rsync -av --exclude='appsettings.json' --exclude='Assets/' ./output/ /var/www/VTA.API/

      - name: Set permissions for the assets folder
        if: github.ref == 'refs/heads/main' && success()
        env:
          SUDO_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
        run: echo "$SUDO_PASSWORD" | sudo -S chmod 777 /var/www/VTA.API/Assets

      - name: Restart the service using SSH
        if: github.ref == 'refs/heads/main' && success()
        env:
          SUDO_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
        run: echo "$SUDO_PASSWORD" | sudo -S systemctl restart vtaapi.service
