name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main  

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test --configuration Release --framework net8.0 --verbosity normal

      - name: Publish the WebAPI
        if: success()  
        run: dotnet publish --configuration Release --output ./output

      - name: Set up SSH key with retries and debugging
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ls -l ~/.ssh  # Check that the SSH key file exists and has correct permissions

          # Retry ssh-keyscan up to 3 times if it fails
          for i in {1..3}; do
            ssh-keyscan ssh_gayraf.mrlarsen.xyz >> ~/.ssh/known_hosts && break
            echo "Retry $i: ssh-keyscan failed. Retrying..."
            sleep 5
          done

          if [ ! -s ~/.ssh/known_hosts ]; then
            echo "ssh-keyscan failed after 3 attempts. Exiting..."
            exit 1
          fi

          chmod 600 ~/.ssh/known_hosts
          echo "Contents of known_hosts:"
          cat ~/.ssh/known_hosts

      - name: Install cloudflared
        if: success()  
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Verify SSH key in use
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o ProxyCommand="cloudflared access ssh --hostname ssh_gayraf.mrlarsen.xyz" fa43lz@ssh_gayraf.mrlarsen.xyz "echo SSH key authentication successful"

      - name: Copy files to server using SCP
        if: success()
        run: |
          scp -o StrictHostKeyChecking=no -o ProxyCommand="cloudflared access ssh --hostname ssh_gayraf.mrlarsen.xyz" -r ./output/* fa43lz@ssh_gayraf.mrlarsen.xyz:/var/www/VTA.API/

      - name: Restart the service using SSH
        if: success()
        run: |
          ssh -o StrictHostKeyChecking=no -o ProxyCommand="cloudflared access ssh --hostname ssh_gayraf.mrlarsen.xyz" fa43lz@ssh_gayraf.mrlarsen.xyz "sudo systemctl restart vtaapi.service"
