name: Auto Set Start Date for Issues

on:
  issues:
    types: [opened]

jobs:
  set-start-date:
    runs-on: ubuntu-latest

    steps:
      - name: Set Start Date for Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_DATE=${{ github.event.issue.created_at }}

          START_DATE=$(echo $ISSUE_DATE | cut -d'T' -f1)

          PROJECT_ID=<your-project-id>
          START_DATE_FIELD_ID=<your-start-date-field-id>

          curl -X POST \
            -H "Authorization: Bearer $GIT_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/cards/${ISSUE_NUMBER} \
            -d '{"field_id": "'${START_DATE_FIELD_ID}'", "value": "'${START_DATE}'"}'
