name: Auto Set Start Date for Issues

on:
  issues:
    types: [opened]

jobs:
  set-start-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Add Start Date as a Comment
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_DATE=$(date +%Y-%m-%d)

          # Post a comment with the start date to the issue
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments \
            -d '{"body": "Start date: '${ISSUE_DATE}'"}'
