name: Auto Set Start Date for Issues

on:
  issues:
    types: [opened]

jobs:
  set-start-date:
    runs-on: ubuntu-latest

    steps:
      - name: Set Start Date in Issue Metadata
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_DATE=$(date +%Y-%m-%d)

          PROJECT_ID="PVT_kwDOAtc8ts4Ao6I3"
          # Field ID for Start Date
          START_DATE_FIELD_ID="PVTF_lADOAtc8ts4Ao6I3zggaK1Y"

          ISSUE_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER} | jq -r '.node_id')

          GRAPHQL_MUTATION='
          mutation {
            updateProjectV2ItemFieldValue(input: {
              projectId: "'${PROJECT_ID}'",
              itemId: "'${ISSUE_ID}'",
              fieldId: "'${START_DATE_FIELD_ID}'",
              value: { text: "'${ISSUE_DATE}'" }
            }) {
              projectV2Item {
                id
              }
            }
          }'

          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GIT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query": "'"$GRAPHQL_MUTATION"'"}' \
            https://api.github.com/graphql
